### ISSUE TITLE
Bolero 0.5 default template application won't do logon

### ISSUE THREAD

**Issue by BentTranberg** [fsbolero/Template#15]
I am using VS 2019 v 16.1.2. I have installed .NET Core 3.0 SDK v 3.0.100-preview5. I have installed the Bolero 0.5 template and created an application as described on the Getting started page.

The application seems to work just fine until I try to logon in the "Download data" page with a username and the password "password". There is no response when I click on the "Sign in" button.

This is from the output pane in VS 2019. I have included irrelevant repeating group of lines before and after the interesting part.

```
BoleroSpike2.Client>       Request starting HTTP/1.1 GET http://localhost:7982/favicon.ico  
BoleroSpike2.Client> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
BoleroSpike2.Client>       The file /index.html was not modified
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 6.125ms 304 text/html
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
BoleroSpike2.Client>       Request starting HTTP/1.1 GET http://localhost:7982/bolero-reload  
BoleroSpike2.Client> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
BoleroSpike2.Client>       Sending file. Request path: '/index.html'. Physical path: 'C:\devbox\BoleroSpike2\src\BoleroSpike2.Client\wwwroot\index.html'
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 5.397600000000001ms 200 text/html
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
BoleroSpike2.Client>       Request starting HTTP/1.1 GET http://localhost:7982/favicon.ico  
BoleroSpike2.Client> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
BoleroSpike2.Client>       The file /index.html was not modified
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 4.3846ms 304 text/html
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
BoleroSpike2.Client>       Request starting HTTP/1.1 GET http://localhost:7982/bolero-reload  
BoleroSpike2.Client> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
BoleroSpike2.Client>       Sending file. Request path: '/index.html'. Physical path: 'C:\devbox\BoleroSpike2\src\BoleroSpike2.Client\wwwroot\index.html'
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 6.0196000000000005ms 200 text/html
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
BoleroSpike2.Client>       Request starting HTTP/1.1 POST http://localhost:7982/books/signIn application/json; charset=utf-8 18
BoleroSpike2.Client> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
BoleroSpike2.Client>       An unhandled exception has occurred while executing the request.
BoleroSpike2.Client> System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
BoleroSpike2.Client> 
BoleroSpike2.Client>    at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
BoleroSpike2.Client>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
BoleroSpike2.Client>    at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
BoleroSpike2.Client>    at Microsoft.AspNetCore.Builder.AutoRebuildExtensions.<>c__DisplayClass4_0.<<UseDevServerAutoRebuild>b__1>d.MoveNext()
BoleroSpike2.Client> --- End of stack trace from previous location where exception was thrown ---
BoleroSpike2.Client>    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
BoleroSpike2.Client>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 5.4442ms 500 text/plain
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
BoleroSpike2.Client>       Request starting HTTP/1.1 GET http://localhost:7982/bolero-reload  
BoleroSpike2.Client> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
BoleroSpike2.Client>       Sending file. Request path: '/index.html'. Physical path: 'C:\devbox\BoleroSpike2\src\BoleroSpike2.Client\wwwroot\index.html'
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 5.0561ms 200 text/html
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
BoleroSpike2.Client>       Request starting HTTP/1.1 GET http://localhost:7982/bolero-reload  
BoleroSpike2.Client> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
BoleroSpike2.Client>       Sending file. Request path: '/index.html'. Physical path: 'C:\devbox\BoleroSpike2\src\BoleroSpike2.Client\wwwroot\index.html'
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 6.0516000000000005ms 200 text/html
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

```

**Comment by Tarmil** [comment]
Fixed in ffbe076.
