### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by jpeg729** [fsbolero/Template#7]
My system
- KUbuntu 18.04 with dotnet 2.2 installed via the official repository.

My actions
- dotnet new -i Bolero.Templates
- dotnet new bolero-app -o Bolero
- cd Bolero
- dotnet run -p src/Bolero.Server

The result
```
Application startup exception: System.ArgumentException: An item with the same key has already been added. Key: .wasm
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.CreateContentTypeProvider(Boolean enableDebugging)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at Bolero.Server.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/user/code/fsharp/Bolero/src/Bolero.Server/Startup.fs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.ArgumentException: An item with the same key has already been added. Key: .wasm
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.CreateContentTypeProvider(Boolean enableDebugging)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at Bolero.Server.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/user/code/fsharp/Bolero/src/Bolero.Server/Startup.fs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: .wasm
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.CreateContentTypeProvider(Boolean enableDebugging)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at Bolero.Server.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/user/code/fsharp/Bolero/src/Bolero.Server/Startup.fs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Bolero.Server.Program.main(String[] args) in /home/user/code/fsharp/Bolero/src/Bolero.Server/Startup.fs:line 41
```

I also tried `dotnet new bolero-app -o ADifferentName` just in case there were conflicts, but it still doesn't work

**Comment by Tarmil** [comment]
Yes, this is a [known issue](https://github.com/aspnet/AspNetCore/issues/5666) with Blazor 0.7 and ASP.NET Core 2.2. It is fixed in Blazor 0.8, and we'll probably upgrade Bolero to it soon, but that will require ASP.NET Core 3.0 (which is currently in preview).

In the meantime, the workaround is to use ASP.NET Core 2.1. You'll need to [install the latest .NET Core 2.1](https://dotnet.microsoft.com/download/dotnet-core/2.1), and I think that's all you have to do. Maybe run `.paket/paket update` too.

**Comment by jpeg729** [comment]
That works, thanks

**Comment by baronfel** [comment]
Ran into this today working with the bolero templates as well. If the templates require certain sdk versions, would it make sense to create a `global.json` with the correct maximal version set?  For example I had to add a `global.json` with the following content to force the correct SDK usage:
```json
{
    "sdk": {
        "version": "2.1.504"
    }
}
```

but really any 2.1.4 or 2.1.5 sdk would be fine I think.

**Comment by Tarmil** [comment]
The problem of global.json is that it forces a specific version, you can't give it a range. If you could say something like `>=2.1.200 < 2.2` (or `~> 2.1.200` in paket syntax :P) then I'd be all over it, but as it stands I'm more hesitant to force users to install a specific SDK.

**Comment by baronfel** [comment]
It's sort of a minimum bound in most cases, actually: (taken from the [docs](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json#matching-rules))

> Starting with .NET Core 2.0, the following rules apply when determining which version of the SDK to use:
>
>    If no global.json file is found or global.json doesn't specify an SDK version, the latest installed SDK version is used. Latest SDK version can be either release or pre-release - the highest version number wins.
>    If global.json does specify an SDK version:
>        If the specified SDK version is found on the machine, that exact version is used.
>        If the specified SDK version can't be found on the machine, the latest installed SDK patch version of that version is used. Latest installed SDK patch version can be either release or pre-release - the highest version number wins. In .NET Core 2.1 and higher, the patch versions lower than the patch version specified are ignored in the SDK selection.
>        If the specified SDK version and an appropriate SDK patch version can't be found, an error is thrown.

So it's a quasi range. It's not a great solution or situation overall, I agree.
